packages:
  - '.'
allowBuilds:
  '@logicflow/core': true
  '@scarf/scarf': true
  core-js: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@fulgurjs/federation@6.4.2'

patchedDependencies:
  tinymce@6.6.2: ../patches/tinymce-6.6.2.patch
