import { chromium } from '@playwright/test'
const BASE = 'http://localhost:8662'
const browser = await chromium.launchPersistentContext(`/tmp/fulgur-diagf5-${Date.now()}`, { headless: true, args: ['--no-proxy-server'], viewport: { width: 1600, height: 900 } })
const page = browser.pages()[0]
const logs = []
page.on('pageerror', (e) => logs.push('[pageerror] ' + String(e).slice(0, 250)))
page.on('console', (m) => { if (m.type() === 'error') logs.push('[console] ' + m.text().slice(0, 250)) })
page.on('response', (r) => { if (r.url().includes('/demo/bpm/model') || r.url().includes('/demo/bpm/category')) logs.push(`[api ${r.status()}] ` + r.url().slice(0, 130)) })
await page.goto(`${BASE}/main/`, { waitUntil: 'domcontentloaded', timeout: 60000 })
await page.waitForTimeout(8000)
await page.locator('input[placeholder*="账号"], input[placeholder*="用户名"]').first().fill('admin')
await page.locator('input[type="password"]').first().fill('Demo@123456')
await page.locator('button:has-text("登 录"), button:has-text("登录")').first().click()
await page.locator('input[type="password"]').first().waitFor({ state: 'hidden', timeout: 30000 }).catch(() => {})
await page.waitForTimeout(3000)
await page.goto(`${BASE}/main/flowable/bpm/manager/model`, { waitUntil: 'domcontentloaded', timeout: 45000 }).catch(() => {})
await page.waitForTimeout(20000)
let st = await page.evaluate(() => ({ catCards: document.querySelectorAll('.rounded-lg').length, textLen: document.body.innerText.length, rows: document.querySelectorAll('.el-table__row').length }))
console.log('t+20s:', JSON.stringify(st))
await page.waitForTimeout(15000)
st = await page.evaluate(() => ({ catCards: document.querySelectorAll('.rounded-lg').length, textLen: document.body.innerText.length, rows: document.querySelectorAll('.el-table__row').length }))
console.log('t+35s:', JSON.stringify(st))
console.log(logs.slice(0, 10).join('\n'))
await page.screenshot({ path: '/tmp/fulgur-08-prod.png' })
await browser.close()
